### ISSUE TITLE
Parameters management

### ISSUE THREAD

**Issue by matteodv99tn** [Thuong-ironman/OCR_2023#1]
I think its better if you write the parameters in an external file (e.g. ``conf.py``) and then call them back inside the two scripts ``get_terminal_cost_data.py`` and ``Integrate_terminal_cost_MPC.py``. As of now, **parameters are out of sync** (min/max joint values).

This is the usual thing that Del Prete does in it scripts

I also noted that for the generation of the data you use a OCP with dt=0.1s and 10 steps, while in ``Integrate_terminal_cost_MPC.py`` you have 100steps (shouldn't that be lower?) of dt=0.01s

**Comment by Thuong-ironman** [comment]
Moved all parameters to conf.py file. 
I also changed dt = 0.01, and increased the length of horizon to 200. But the total cost is still high.
