### ISSUE TITLE
OCP Formulation

### ISSUE THREAD

**Issue by matteodv99tn** [Thuong-ironman/OCR_2023#2]
Similar to issue #1, I would move the formulation of the OCP problem in another script.
If possible I would use the same OCP object for both part of the project.
I would create the ``OcpSinglePendulum`` that can be used simply for the first part of the project (generation of the dataset).
Then I would use inheritance to create ``OcpSinglePendulumWithNNCost`` that extends ``OcpSinglePendulum`` by simply adding the terminal cost as evaluated by the neural network.

**Note:** I assume that you are quite familiar with Python and object inheritance. If not, let me know by writing here and ping me so I don't miss the thread.

**Comment by matteodv99tn** [comment]
For this part I would split the definition of the OCP problem and the solution, like

``` python
class OcpSinglePendulum:
    def __init__(self, ...): 
        # ...
        pass

    def problem_setup(self, ... config values): 
        # Here you define the parameters of the ocp
        # In this way while extending the class you can reuse the previously defined code
        pass

    def solve(self): 
        return self.opti.solve()
```

**Comment by Thuong-ironman** [comment]
Could you please review the file Integrate_terminal_cost_MPC.py to make sure I follow the right MPC algorithm?
I'm starting with initial state  * x = [pi/2, 0]* and control input * U = [0,..,0]* N steps. 
Then starting the loop:
i from 0 to N:
 U* = solve ocp(xi, Uguess = U)
 xi+1 = dynamics(xi, u = U*[0])
 U = np.pad(U[1:N], (0, 1), 'constant') #pad 0 at the end of U

I got an issue that is:
 x[i+1,0] = dt*x[i,1] #dynamics
IndexError: index 200 is out of bounds for axis 0 with size 200

**Comment by Thuong-ironman** [comment]
once the code is able to run, I will factorize the formulation of the OCP problem later  @matteodv99tn

**Comment by matteodv99tn** [comment]
[Here](https://github.com/Thuong-ironman/OCR_2023/blob/58dee4b2446431601da1428a9c50fa6f8ef04b1b/Integrate_terminal_cost_MPC.py#L93C9-L95C80) the issue is related to the index up to which you integrate. You should integrate up to ``N-1``.
The issue is that at each iteration index ``i`` you are writing to state ``i+1``. 

I imagine that you set ``N=200``, thus ``range(N)`` yields ``i`` from ``0`` to ``199``, but at the last step you are writing to ``i+1=200`` which is not valid (since ``x`` is has size ``200``, valid indexes are ``0`` to ``199``)

**Comment by matteodv99tn** [comment]
BTW next time instead of copy-paste code snippets I think it's easier if you use [permalinks as reported here](https://stackoverflow.com/questions/27615972/how-can-i-use-a-link-to-source-code-in-github-issue). This drives me exactly to the code section you asked me without problem.
Then use markdown syntax to embed permalink inside the issue

**Comment by Thuong-ironman** [comment]
When I run MPC over N = 200 time steps, I don't know why the system was converge so quickly which is at the 2 steps.
![Figure_1](https://github.com/Thuong-ironman/OCR_2023/assets/19421386/b1f0e900-0fc7-4ac8-8b68-c29d063b2651)

**Comment by matteodv99tn** [comment]
This shouldn't be possible.
How many cycles does the solver take to reach it's optimal solution?

I will try to look later more deeply at the code
In the mean time I will highly suggest you to refactor the code as I told you above, it will ease next steps
I mean, at this point in time you should just copy the [``OcpSinglePendulum``](https://github.com/Thuong-ironman/OCR_2023/blob/f43a10a89d63b041aa47b116d70e7f78a489a0b7/get_terminal_cost_data.py#L4-L66) in another file and import it in the script used for the data generation

**Comment by matteodv99tn** [comment]
I didn't check properly... Did you bound the effort on your input? Can you check if the inputs are either satured or very high values?

**Comment by Thuong-ironman** [comment]
When I change the bounded input to -10 to 10, or -5 to 5, the inputs are always reach to the saturation value @matteodv99tn

**Comment by matteodv99tn** [comment]
And still states are always zero (aside the first one)?

**Comment by Thuong-ironman** [comment]
Yes, the states are always zero from the second state forward @matteodv99tn

**Comment by Thuong-ironman** [comment]
The number of cycles that solver take to reach the optimal solution is n_eval in the picture below, right?
![Screenshot from 2024-01-17 21-14-23](https://github.com/Thuong-ironman/OCR_2023/assets/19421386/cd7a40d5-48f5-4191-bc72-a83fd1a1f6ad)

**Comment by matteodv99tn** [comment]
I think that these are function evaluation to estimate different functions and their gradients
Overall it seems to take 1 evaluation to find the solution (i.e. the first guess is considered already optimal)
Probabibly the OCP formulation is not correct

**Comment by Thuong-ironman** [comment]
Hi @matteodv99tn , I factorize the code by moving OCP problem to another file, create the https://github.com/Thuong-ironman/OCR_2023/blob/b5b40a7aff4eea136e968212b5d882780eae84d2/OCP_SinglePendulum.py#L8 for the first part and https://github.com/Thuong-ironman/OCR_2023/blob/b5b40a7aff4eea136e968212b5d882780eae84d2/OCP_SinglePendulum.py#L82 for integrating terminal cost in OCP problem.

**Comment by matteodv99tn** [comment]
Why [here](https://github.com/Thuong-ironman/OCR_2023/blob/b5b40a7aff4eea136e968212b5d882780eae84d2/Integrate_terminal_cost_MPC.py#L10-L112)  you have the OCP problem commented out? Just remove it and that's it..
