### ISSUE TITLE
Wrongly define OCP problem

### ISSUE THREAD

**Issue by Thuong-ironman** [Thuong-ironman/OCR_2023#4]
Hi @matteodv99tn , I figured out that I wrongly define the system dynamic in OCP problem. The next state should be equal to previous state + dt*(u,x) like I defined it here: 
https://github.com/Thuong-ironman/OCR_2023/blob/caacfd33b256443b76c38361af023886d5c51040/OCP_SinglePendulum.py#L61-L62

When I start at a specific state x:
https://github.com/Thuong-ironman/OCR_2023/blob/caacfd33b256443b76c38361af023886d5c51040/Integrate_terminal_cost_MPC.py#L48

Here is the plot of position state x after 200 iteration 
![Figure_1](https://github.com/Thuong-ironman/OCR_2023/assets/19421386/1cfe13cb-2080-42ed-aae4-aef7c232e0bd)

Does it make sense?

**Comment by matteodv99tn** [comment]
This is definitively more likely. Can you show me also the torques? Are they saturated?

**Comment by Thuong-ironman** [comment]
The torque is something like this
![controlInput_state](https://github.com/Thuong-ironman/OCR_2023/assets/19421386/bb7133d8-0928-4e99-8048-99679e6cf4ad)

**Comment by matteodv99tn** [comment]
Try the following 2 options:

1. Remove cost of the torque
2. Add hard constraints on the final states

Any how, this results are good for me as ocp results

**Comment by Thuong-ironman** [comment]
Good to hear that @matteodv99tn,
I tried to reduce cost of the torque by setting w_u to very small value 1e-10. The results are look the same
![Figure_3](https://github.com/Thuong-ironman/OCR_2023/assets/19421386/f8a60dd1-586c-4774-af3f-7ab161284185)

And, this is the result when I added hard constraints to the final states like this:
https://github.com/Thuong-ironman/OCR_2023/blob/576e25a228bfa1f066b229da091fb2744c56931a/OCP_SinglePendulum.py#L74

Got the results here:
![Figure_4](https://github.com/Thuong-ironman/OCR_2023/assets/19421386/f1d0b87f-7413-4fc0-ab5b-271c287841c5)

I'm trying to reduce the length of the horizon to N = 100 or 50 now to see whether it is able to converge or not.

**Comment by matteodv99tn** [comment]
Still you are converging, so it's fine.
Maybe the cost on the velocity is slowing down the convergence.

But its fine. Continue with the whole project by training the network
